# fly.toml app configuration file generated for athlead-sse-relay on 2026-09-30T08:26:26Z
#
# See https://docs.fly.io/reference/configuration for information about how to use this file.
#

app = 'athlead-sse-relay'
primary_region = 'ams'

[build]
  dockerfile = 'Dockerfile'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 2
  checks = [{ grace_period = '5s', interval = '10s', method = 'GET', path = '/health', timeout = '2s' }]
  concurrency = { hard_limit = 3500, soft_limit = 2500, type = 'connections' }

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 256

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 2
  memory_mb = 512
  processes = ['app']
  size = 'shared-cpu-2x'
